from django.urls import path

from .views import *

urlpatterns = [
    path("logout", LogoutAPIView.as_view(), name="logout"),
    path("system_admin/dashboard", SystemAdminOnlyView.as_view()),
    path("student/dashboard", StudentOnlyView.as_view()),
    path("teacher/dashboard", TeacherOnlyView.as_view()),
    path("language_native/dashboard", LanguageNativeOnlyView.as_view()),
    path("login", CustomAuthToken.as_view(), name="auth-token"),
    path("signup/system_admin", SystemAdminSignupAPIView.as_view()),
    path("signup/student", StudentSignupAPIView.as_view()),
    path("signup/teacher", TeacherSignupAPIView.as_view()),
    path("signup/language_native", LanguageNativeSignupAPIView.as_view()),
    path("speaking_exercises", SpeakingExerciseListView.as_view()),
    path("speaking_exercises/<int:exercise_id>",
         SpeakingExerciseAPIView.as_view()),
    path("homeworks", HomeworkListView.as_view()),
    path("homeworks/<int:homework_id>", HomeworkAPIView.as_view()),
    path("forum_topics", ForumTopicListView.as_view()),
    path("forum_topics/<int:topic_id>", ForumTopicAPIView.as_view()),
    path("requested_exercises", RequestExerciseListView.as_view()),
    path("requested_exercises/<int:request_id>",
         RequestExerciseAPIView.as_view()),
    path("levels", LevelListView.as_view()),
    path("levels/<int:level_id>", LevelAPIView.as_view()),
    path("tags", TagListView.as_view()),
    path("tags/<int:tag_id>", TagAPIView.as_view()),
    path("rated_exercise_details", RateExerciseDetailsListView.as_view()),
    path("rated_exercise_details/<int:detail_id>",
         RateExerciseDetailsAPIView.as_view()),
    path("classes", ClassListAPIView.as_view()),
    path("classes/<int:classId>", ClassAPIView.as_view()),
    path("class_books", ClassBookListAPIView.as_view()),
    path("class_books/<int:classBookId>", ClassBookAPIView.as_view()),
    path("languages", LanguageListAPIView.as_view()),
    path("languages/<int:languageId>", LanguageAPIView.as_view()),
    path("forum_reply_comments", ForumReplyCommentListAPIView.as_view()),
    path("forum_reply_comments/<int:forumReplyCommentId>",
         ForumReplyCommentAPIView.as_view()),
    path("uploaded_homeworks", UploadedHomeworkListAPIView.as_view()),
    path("uploaded_homeworks/<int:uploadedHomeworkId>",
         UploadedHomeworkAPIView.as_view()),
    path("forum_replies", ForumReplyListAPIView.as_view()),
    path("forum_replies/<int:forumReplyId>", ForumReplyAPIView.as_view()),
    path("class_ratings", ClassRatingListAPIView.as_view()),
    path("class_ratings/<int:classRatingId>", ClassRatingAPIView.as_view()),
    path("find_native_speakers", FindNativeSpeakerListAPIView.as_view()),
    path("forum_topic_filter", FilterForumTopicListAPIView.as_view()),

    path("ungraded_exercises_native",
         UngradedSpeakingExercisesListViewForLanguageNative.as_view()),
    path("graded_exercises_native",
         GradedSpeakingExercisesListViewForLanguageNative.as_view()),
    path("upcoming_exercises_native",
         UpcomingSpeakingExercisesListViewForLanguageNative.as_view()),
    path("past_exercises_native",
         PastSpeakingExercisesListViewForLanguageNative.as_view()),
    path("requested_exercises_native",
         RequestedSpeakingExercisesListViewForLanguageNative.as_view()),
    path("declined_exercises_native",
         DeclinedRequestedSpeakingExercisesListViewForLanguageNative.as_view()),
    path("accepted_exercises_native",
         AcceptedRequestedSpeakingExercisesListViewForLanguageNative.as_view()),

    path("find_classes", FindClassesListAPIView.as_view()),
    path("my_classes", ClassesOfStudentListAPIView.as_view()),
    path("exercises_student", SpeakingExercisesListAPIViewForStudent.as_view()),
    path("upcoming_exercises_student",
         UpcomingSpeakingExercisesListAPIViewForStudent.as_view()),
    path("requested_exercises_student",
         RequestedSpeakingExercisesListAPIViewForStudent.as_view()),
    path("language_natives", LanguageNativeListAPIView.as_view()),
    path("request_exercise", RequestSpeakingExerciseAPIView.as_view()),
    path("grades_homeworks_student", HomeworkGradesListAPIViewForStudent.as_view()),
    path("exercises_homeworks_student",
         ExerciseGradesListAPIViewForStudent.as_view()),
    path("classes_teacher", ClassesListAPIViewForTeacher.as_view()),
    path("class_requests_teacher", ClassRequestsListAPIViewForTeacher.as_view()),
    path("admin_num_students", AdminReportNumOfStudentsAPIView.as_view()),
    path("admin_exercise_average", AdminReportExerciseAveragesAPIView.as_view()),
    path("admin_homework_average", AdminReportHomeworkAveragesAPIView.as_view()),

]
