# Generated by Django 4.0.4 on 2022-05-16 09:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.IntegerField()),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('duration', models.IntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('weekly_plan', models.TextField()),
                ('enrollment', models.IntegerField()),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Class_Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('due_datetime', models.DateTimeField()),
                ('assign_datetime', models.DateTimeField()),
                ('grade', models.FloatField()),
                ('given_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='levelup_api.class')),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang_name', models.CharField(max_length=80, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_title', models.CharField(max_length=80, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Request_Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_datetime', models.DateTimeField()),
                ('status', models.CharField(max_length=20)),
                ('additional_notes', models.TextField()),
                ('created_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='System_Admin',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='levelup_api.user')),
            ],
        ),
        migrations.CreateModel(
            name='System_User',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='levelup_api.user')),
                ('date_birth', models.DateField()),
                ('photo', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Speaking_Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_link', models.TextField()),
                ('exercise_datetime', models.DateTimeField()),
                ('grade', models.FloatField()),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='levelup_api.language')),
            ],
        ),
        migrations.CreateModel(
            name='Rate_Exercise_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.FloatField()),
                ('review', models.TextField()),
                ('rate_datetime', models.DateTimeField()),
                ('speaking_exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='levelup_api.speaking_exercise')),
            ],
        ),
        migrations.CreateModel(
            name='Rate_Class_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.FloatField()),
                ('rate_datetime', models.DateTimeField()),
                ('given_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='levelup_api.class')),
            ],
        ),
        migrations.CreateModel(
            name='Forum_Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('status', models.CharField(max_length=20)),
                ('topic_title', models.TextField()),
                ('topic_text', models.TextField()),
                ('tags', models.ManyToManyField(db_table='levelup_api_topic_tags', to='levelup_api.tag')),
                ('topic_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='levelup_api.system_user')),
            ],
        ),
        migrations.CreateModel(
            name='Forum_Reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('reply_text', models.TextField()),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='levelup_api.forum_topic')),
                ('reply_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='levelup_api.system_user')),
            ],
        ),
        migrations.AddField(
            model_name='class',
            name='books',
            field=models.ManyToManyField(db_table='levelup_api_require_books', to='levelup_api.class_book'),
        ),
        migrations.AddField(
            model_name='class',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='levelup_api.language'),
        ),
        migrations.AddField(
            model_name='class',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='levelup_api.level'),
        ),
        migrations.CreateModel(
            name='Language_Native',
            fields=[
                ('system_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='levelup_api.system_user')),
                ('description', models.TextField()),
                ('rating', models.FloatField()),
                ('speaks', models.ManyToManyField(db_table='levelup_api_speaks', to='levelup_api.language')),
            ],
        ),
        migrations.CreateModel(
            name='Forum_Reply_Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('comment_text', models.TextField()),
                ('reply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='levelup_api.forum_reply')),
                ('comment_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='levelup_api.system_user')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('system_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='levelup_api.system_user')),
                ('description', models.TextField()),
                ('rating', models.FloatField()),
                ('yearsOfExperience', models.IntegerField()),
                ('languages', models.ManyToManyField(db_table='levelup_api_knows', to='levelup_api.language')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('system_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='levelup_api.system_user')),
                ('contact_no', models.CharField(max_length=12)),
                ('classes', models.ManyToManyField(db_table='levelup_api_takes', related_name='classes', to='levelup_api.class')),
                ('homeworks', models.ManyToManyField(db_table='levelup_api_get_hw', to='levelup_api.homework')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='levelup_api.level')),
                ('rate_class', models.ManyToManyField(related_name='rate_class', through='levelup_api.Rate_Class_Details', to='levelup_api.class')),
                ('rate_exercise', models.ManyToManyField(related_name='rate_exercise', through='levelup_api.Rate_Exercise_Details', to='levelup_api.speaking_exercise')),
                ('requested_class', models.ManyToManyField(db_table='levelup_api_request_class', to='levelup_api.class')),
                ('requested_exercise', models.ManyToManyField(through='levelup_api.Request_Exercise', to='levelup_api.language_native')),
            ],
        ),
        migrations.AddField(
            model_name='speaking_exercise',
            name='language_native',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='levelup_api.language_native'),
        ),
        migrations.AddField(
            model_name='speaking_exercise',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='levelup_api.student'),
        ),
        migrations.AddField(
            model_name='request_exercise',
            name='language_native',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='levelup_api.language_native'),
        ),
        migrations.AddField(
            model_name='request_exercise',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='levelup_api.student'),
        ),
        migrations.AddField(
            model_name='rate_exercise_details',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='levelup_api.student'),
        ),
        migrations.AddField(
            model_name='rate_class_details',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='levelup_api.student'),
        ),
        migrations.CreateModel(
            name='Homework_Upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_datetime', models.DateTimeField()),
                ('date', models.FileField(upload_to='')),
                ('homework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='levelup_api.homework')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='levelup_api.student')),
            ],
        ),
        migrations.AddField(
            model_name='class',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='levelup_api.teacher'),
        ),
    ]
