<<<<<<< Updated upstream
# Generated by Django 4.0.4 on 2022-05-15 12:17
=======
# Generated by Django 4.0.4 on 2022-05-15 11:38
>>>>>>> Stashed changes

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
<<<<<<< Updated upstream
                ('capacity', models.IntegerField()),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('duration', models.IntegerField()),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('weeklyPlan', models.TextField()),
                ('enrollment', models.IntegerField()),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='ClassBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookName', models.TextField()),
=======
>>>>>>> Stashed changes
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LanguageNative',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='levelup_api.user')),
                ('description', models.TextField()),
                ('rating', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='levelup_api.user')),
                ('contactNo', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='SystemAdmin',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='levelup_api.user')),
            ],
        ),
        migrations.CreateModel(
            name='SystemUser',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='levelup_api.user')),
                ('dateBirth', models.DateField()),
                ('photo', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='levelup_api.user')),
                ('description', models.TextField()),
                ('rating', models.FloatField()),
                ('yearsOfExperience', models.IntegerField()),
            ],
        ),
<<<<<<< Updated upstream
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('dueDatetime', models.DateTimeField()),
                ('assignDatetime', models.DateTimeField()),
                ('grade', models.FloatField()),
                ('givenClass', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='levelup_api.class')),
            ],
        ),
        migrations.AddField(
            model_name='class',
            name='books',
            field=models.ManyToManyField(db_table='require_books', to='levelup_api.classbook'),
        ),
        migrations.CreateModel(
            name='SpeakingExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exerciseLink', models.TextField()),
                ('exerciseDatetime', models.DateTimeField()),
                ('grade', models.FloatField()),
                ('languageNative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='levelup_api.languagenative')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='levelup_api.student')),
            ],
        ),
        migrations.AddField(
            model_name='class',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='levelup_api.teacher'),
        ),
=======
>>>>>>> Stashed changes
    ]
