# Generated by Django 4.0.4 on 2022-05-15 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levelup_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='books',
            field=models.ManyToManyField(db_table='levelup_api_require_books', to='levelup_api.classbook'),
        ),
    ]
