# Generated by Django 4.0.4 on 2022-05-17 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('levelup_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
    ]
