# Generated by Django 4.0.4 on 2022-05-17 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('levelup_api', '0004_user_groups_user_is_superuser_user_user_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language_native',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='language_native',
            name='rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='language_native',
            name='speaks',
            field=models.ManyToManyField(blank=True, db_table='levelup_api_speaks', null=True, to='levelup_api.language'),
        ),
        migrations.AlterField(
            model_name='student',
            name='classes',
            field=models.ManyToManyField(blank=True, db_table='levelup_api_takes', null=True, related_name='classes', to='levelup_api.class'),
        ),
        migrations.AlterField(
            model_name='student',
            name='contact_no',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='homeworks',
            field=models.ManyToManyField(blank=True, db_table='levelup_api_get_hw', null=True, to='levelup_api.homework'),
        ),
        migrations.AlterField(
            model_name='student',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='levelup_api.level'),
        ),
        migrations.AlterField(
            model_name='student',
            name='rate_class',
            field=models.ManyToManyField(blank=True, null=True, related_name='rate_class', through='levelup_api.Rate_Class_Details', to='levelup_api.class'),
        ),
        migrations.AlterField(
            model_name='student',
            name='rate_exercise',
            field=models.ManyToManyField(blank=True, null=True, related_name='rate_exercise', through='levelup_api.Rate_Exercise_Details', to='levelup_api.speaking_exercise'),
        ),
        migrations.AlterField(
            model_name='student',
            name='requested_class',
            field=models.ManyToManyField(blank=True, db_table='levelup_api_request_class', null=True, to='levelup_api.class'),
        ),
        migrations.AlterField(
            model_name='student',
            name='requested_exercise',
            field=models.ManyToManyField(blank=True, null=True, through='levelup_api.Request_Exercise', to='levelup_api.language_native'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='languages',
            field=models.ManyToManyField(blank=True, db_table='levelup_api_knows', null=True, to='levelup_api.language'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='yearsOfExperience',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
