# Generated by Django 4.0.4 on 2022-05-17 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levelup_api', '0008_alter_user_created_at_alter_user_updated_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='yearsOfExperience',
            new_name='years_of_experience',
        ),
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.TextField(default='https://www.google.com.tr/url?sa=i&url=https%3A%2F%2Fpixabay.com%2Fvectors%2Favatar-icon-placeholder-facebook-1577909%2F&psig=AOvVaw0oRznk6nZxb2qFn3fZnTa1&ust=1652886795297000&source=images&cd=vfe&ved=0CAwQjRxqFwoTCIDA0rTp5vcCFQAAAAAdAAAAABAD', null=True),
        ),
    ]
