# Generated by Django 4.0.4 on 2022-05-17 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('levelup_api', '0009_rename_yearsofexperience_teacher_years_of_experience_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='languages',
            new_name='knows',
        ),
    ]
