# Generated by Django 4.0.4 on 2022-05-17 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levelup_api', '0010_rename_languages_teacher_knows'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='lang_name',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='language_native',
            name='speaks',
            field=models.ManyToManyField(blank=True, db_table='levelup_api_speaks', null=True, related_name='speaks', to='levelup_api.language'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='knows',
            field=models.ManyToManyField(blank=True, db_table='levelup_api_knows', null=True, related_name='knows', to='levelup_api.language'),
        ),
    ]
