# Generated by Django 4.0.4 on 2022-05-17 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levelup_api', '0011_alter_language_lang_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='level_title',
            field=models.CharField(max_length=80),
        ),
    ]
