# Generated by Django 4.0.4 on 2022-05-17 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levelup_api', '0013_remove_student_level_remove_user_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speaking_exercise',
            name='grade',
            field=models.FloatField(default=None, null=True),
        ),
    ]
