# Generated by Django 4.0.4 on 2022-05-18 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levelup_api', '0014_alter_speaking_exercise_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='image',
            field=models.ImageField(default=None, upload_to=''),
        ),
        migrations.AlterField(
            model_name='homework',
            name='grade',
            field=models.FloatField(default=None),
        ),
        migrations.AlterField(
            model_name='request_exercise',
            name='status',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='speaking_exercise',
            name='grade',
            field=models.FloatField(default=None),
        ),
    ]
